- package.json
- src/assets/styles/_custom-variable.scss
- src/assets/styles/_external.scss
- src/assets/styles/_normalize.scss
- src/assets/styles/main.scss
- src/components/berths/Berth/BerthDetails/_styles.scss
- src/components/berths/Berth/SelectedBerth/_styles.scss
- src/components/berths/Berth/_styles.scss
- src/components/berths/_styles.scss
- src/components/common/Icon/Icon.scss
- src/components/common/Icon/Icon.test.tsx
- src/components/common/Icon/_styles.scss
- src/components/common/Icon/index.tsx
- src/components/common/_styles.scss
- src/components/forms/sections/SectionSelector/_styles.scss
- src/components/forms/sections/_styles.scss
- src/components/layout/Footer/_styles.scss
- src/components/layout/Navbar/_styles.scss
- src/components/legends/BerthLegend/_styles.scss
- src/components/pages/BerthPage/SelectedBerthPage/_styles.scss
- yarn.lock
- Remove React-svg usage cause nested DOM (hard to style), not actually necessary with help of CRA v2.
- Clean up global stylings
> Remove react-svg, refactor stylings

- src/components/forms/fragments/PostalDetails.tsx
Merging hotfix back to develop
https://github.com/City-of-Helsinki/berth-reservations-ui/pull/178
> VEN-65 | make address, zip_code and municipality fields mandator

- .dockerignore
- .gitlab-ci.yml
- package.json
- Add `.dockerignore`
- Specify redux-devtools-extension as not dev dependency
- Prod pipeline trigger fix
> VEN-760 | Kuva test env fixes

- src/components/App.tsx
- src/components/pages/paymentPage/PaymentPage.tsx
- src/components/pages/paymentPage/paymentPage.scss
- src/locales/fi.json
- Payment page layout (it should work with desktop, tablet and mobile)
- Enable pay button based on accept terms checkbox
- Translations for sv and en missing
- The actual "terms PDF" file is missing
- Land to http://localhost:3000/fi/payment
[VEN-748](https://helsinkisolutionoffice.atlassian.net/browse/VEN-748)
> VEN-748 | Implement payment page layout

- src/components/App.tsx
- src/components/layout/navbar/Navbar.tsx
- src/components/pages/frontPage/FrontPage.tsx
- src/components/pages/frontPage/frontPage.scss
- src/utils/featureFlags.ts
Put unmarked winter storage behind feature flag
If you turn the flag in `featureFlags.ts` manually `false`:
- Unmarked WS top navi item should be hidden
- Unmarked WS card should be hidden in front page
- http://localhost:3000/fi/unmarked-winter-storage should say 404
> VEN-792 | Put unmarked winter storage behind feature flag

- src/components/common/noticeTemplate/NoticeTemplate.tsx
- src/components/common/noticeTemplate/noticeTemplate.scss
- src/locales/en.json
- src/locales/sv.json
- Update en and sv translations for payments
- Improve notice template layout
- the layout had problems with longer text content in mobile (no proper paddings and margins were in place)
- [VEN-810](https://helsinkisolutionoffice.atlassian.net/browse/VEN-810)
- Land to `http://localhost:3000/sv/payment-result?payment_status=success`
- Switch to mobile view via dev tools
- You should see that text content has left and right padding and button should take the whole width with a padding
- Text content should be in sv
> VEN-810 | Update translations

- src/components/pages/unmarkedWinterStoragePage/UnmarkedWinterStoragePage.tsx
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
* Add missing translations for continue button
* [VEN-758](https://helsinkisolutionoffice.atlassian.net/browse/VEN-758): Add missing translations
* Jatka/Fortsätt/Continue button on unmarked winter storage form should now be translated accordingly
> VEN-758 | Translate continue button

- src/assets/styles/_normalize.scss
Remove the padding value for `custom-select` from `_normalize` partial
**Before:**
**After:**
> Fix custom-select padding

- src/components/layout/footer/Footer.tsx
- src/components/pages/berthPage/BerthPage.tsx
- src/components/pages/frontPage/FrontPage.tsx
- src/components/pages/paymentPage/PaymentPage.tsx
- src/components/pages/unmarkedWinterStoragePage/UnmarkedWinterStoragePage.tsx
- src/components/pages/winterStoragePage/WinterStorageNotice.tsx
- src/components/pages/winterStoragePage/WinterStoragePage.tsx
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
* Open external links in new tab
* [VEN-893](https://helsinkisolutionoffice.atlassian.net/browse/VEN-893): FE: Customer contract (shown before the customer proceeds to Bambora payment page) should open in a new tab/window
* Check that contract terms open in new tab
* Check that footer links open in new tab
* Check that all external links on the first form pages open in new tab
> VEN-893 | Open external links in new tab

- .gitlab-ci.yml
Change the urls in review and staging to point to the new KUVA-hosted backend endpoint for the customer ui as well.
VEN-863
> Change review and staging urls to point to new backend

- src/components/forms/fragments/PostalDetails.tsx
- src/constants/Municipalities.ts
Prioritized municipalities should appear twice in the select: at the top, and in the full list, with a divider in between.
[VEN-892](https://helsinkisolutionoffice.atlassian.net/browse/VEN-892)
> VEN-892 | Separate prioritized municipalities in PostalDetails

- .testcaferc.json
- .travis.yml
- README.md
- browser-tests/berth.ts
- browser-tests/frontPage.ts
- browser-tests/selectors/berth.ts
- browser-tests/selectors/berths.ts
- browser-tests/selectors/footer.ts
- browser-tests/selectors/frontPage.ts
- browser-tests/selectors/navbar.ts
- browser-tests/selectors/shared.ts
- browser-tests/selectors/unmarkedWinterStorage.ts
- browser-tests/selectors/winterStorage.ts
- browser-tests/sharedTests/sharedTests.ts
- browser-tests/types/types.ts
- browser-tests/unmarkedWinterStorage.ts
- browser-tests/utils/navigation.ts
- browser-tests/utils/page.ts
- browser-tests/utils/settings.ts
- browser-tests/utils/sharedTests.ts
- browser-tests/utils/switchLanguage.ts
- browser-tests/winterStorage.ts
- package.json
- yarn.lock
Added TestCafe browser tests for
* Navigation and language switching
* Form filling (without sending)
* New berth application, registered boat, private customer
* Winter storage application, registered boat on trailer, private customer
* Unmarked winter storage notice, registered boat on trailer, private customer
Note: Missing cron job from Travis
* [VEN-808](https://helsinkisolutionoffice.atlassian.net/browse/VEN-808): Implement happy path E2E tests for customer UI
* Browser tests can be executed locally by first running the `start` npm script, and then running the `browser-test:local` npm script in another terminal
> VEN-808 | Browser tests

- src/components/pages/paymentPage/PaymentPage.tsx
* Correct customer service email address
* [VEN-1013](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1013): Wrong boat office customer service email-address when customer goes to customer UI from the payment information email link
> VEN-1013 | Correct customer service email address

- .env
- .gitlab-ci.yml
- src/__generated__/globalTypes.ts
- src/components/pages/paymentPage/ContractPage.tsx
- src/components/pages/paymentPage/PaymentPage.tsx
- src/components/pages/paymentPage/PaymentPageContainer.test.tsx
- src/components/pages/paymentPage/PaymentPageContainer.tsx
- src/components/pages/paymentPage/authButton/AuthButton.tsx
- src/components/pages/paymentPage/authButton/authButton.scss
- src/components/pages/paymentPage/paymentPage.scss
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
- src/utils/__generated__/ContractAuthMethods.ts
- src/utils/__generated__/ContractSigned.ts
- src/utils/__generated__/FulfillContract.ts
- src/utils/__generated__/OrderDetails.ts
- src/utils/formValidation.test.ts
- src/utils/formValidation.ts
- src/utils/graphql.ts
- src/utils/urls.test.ts
- src/utils/urls.ts
Adds contract signing step to payments:
- `PaymentPageContainer` fetches order's contract signed status
- If `null` there's no contract information for the order and proceed directly to payments (additional products case)
- If `false` show the new contract signing page
- If `true`, the contract is already signed and display the payment page
[VEN-976](https://helsinkisolutionoffice.atlassian.net/browse/VEN-976)
Updated relevant tests, added tests for ssn validator.
- Handle an application in the admin UI
- Use the generated order number to navigate to `url-to-customer-ui/fi/payment?order_number=...`
- Should display the new contract signing page
- After authentication should redirect to payments page
The ssn field has been removed from the current implementation as we received information …
> VEN-976 | Add contract signing step to payment flow

- src/components/pages/paymentPage/PaymentPageContainer.tsx
* Move error above loading in payment page display priority
* [VEN-1055](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1055): If invalid order_number given as parameter to /payment, no error is shown
* Open http://localhost:3000/fi/payment?order_number=qwerty and expect to see an error
> VEN-1055 | Move error above loading in payment page display priority

- src/components/forms/fragments/CompanyDetails.tsx
- src/components/forms/fragments/FullName.tsx
- src/components/forms/fragments/PostalDetails.tsx
- src/components/forms/fragments/RegisteredBoatDetails.tsx
- src/locales/fi.json
- src/utils/formValidation.test.ts
- src/utils/formValidation.ts
* Validate first name, last name, company name, business id, address, postal code and boat registration number fields
* Fix minor typo in trailer registration
* [VEN-1067](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1067): Customer UI form values should be validated
* Added tests for new validations
* Go nuts with the field values. All fields (except boat name, model and trailer registration number) should be validated
> VEN-1067 | Validate form fields

- browser-tests/berth.ts
- browser-tests/selectors/berth.ts
- src/app/App.tsx
- src/components/pages/cancelOrderPage/cancelOrderPage.scss
- src/components/pages/paymentPage/ContractPage.tsx
- src/components/pages/paymentPage/PaymentPageContainer.tsx
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
- src/utils/formValidation.ts
- src/utils/urls.test.ts
- src/utils/urls.ts
- Add a button that leads to the [`cancel order`](https://venepaikka.test.kuva.hel.ninja/fi/cancel-order) page
[VEN-1096](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1096): Add possibility to terminate lease into customer UI payment view
Added tests:
https://github.com/City-of-Helsinki/berth-reservations-ui/blob/b3821a828d04d3868a3e8c0f3db056955c17ba82/src/utils/urls.test.ts#L21
- From the [payment page](http://localhost:3000/sv/payment?order_number=ajor7vexqi3qa)
- Click on `Irtisano venepaikka` button
- The user should be directed to the [`cancel order`](https://venepaikka.test.kuva.hel.ninja/fi/cancel-order) page
- By following the steps on the cancellation page the lease should be terminated
> VEN-1096 | Add possibility to terminate lease into customer UI payment view

- src/components/pages/paymentPage/ContractPage.tsx
- src/components/pages/paymentPage/paymentPage.scss
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
* Add info text in payment page before terms link
* [VEN-1088](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1088): Add info text in payment page before terms link
> VEN-1088 | Add info text in payment page before terms link

- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
* Add missing REACT_APP_API_URL_ROOT to GitHub workflows
* [VEN-1145](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1145): Payments terms and conditions link shows 404 page
> VEN-1145 | Add missing REACT_APP_API_URL_ROOT to GitHub workflows

- src/features/profile/ProfilePage.tsx
- src/features/profile/ProfilePageContainer.tsx
- src/features/profile/contactInfo/ContactInfo.tsx
- src/features/profile/contactInfo/contactInfo.scss
- src/features/profile/profilePage.scss
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
- Implement the ContactInformation component
- Pass the mock data down from the container to the corresponding tab
[VEN-1102](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1102): Customer contact information page
- Check the contact information tab from [the profile page](https://venepaikka.test.kuva.hel.ninja/fi/profile)
> VEN-1102 | Customer contact information view

- src/features/profile/customerBerths/NoBerths.tsx
- src/features/profile/customerBerths/noBerths.scss
- src/features/profile/profilePage.scss
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
- Adding a Redirect Button
- Fix HDS Tabs padding issue after build
[VEN-1108](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1108): Customer berth page
> VEN-1108 | Profile - Berth View: Adding a Redirect Button

- browser-tests/selectors/shared.ts
- package.json
- src/app/App.tsx
- src/features/payment/cancelOrderPage/CancelOrderPageContainer.tsx
- src/features/payment/cancelOrderPage/OrderCancelledPage.tsx
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
- yarn.lock
* Add success page for cancelling invoice/berth
* [VEN-1120](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1120): Add success page for cancelling invoice/berth
* Once an order is cancelled, the user should be redirected to the success page
* The page is at URL `/fi/order-cancelled`
> VEN-1120 | Add success page for cancelling invoice/berth

- src/features/profile/ProfilePage.tsx
- src/features/profile/customerBerths/CustomerBerths.tsx
- src/features/profile/customerBerths/berthApplication/BerthApplication.tsx
- src/features/profile/profilePage.scss
- Keep the red navigation indicator active until the invoice status is paid or rejected/terminated
- Remove the checkbox `Haluan että hakemus jää voimaan…`
- Pass a prop for enabling and disabling `Muokkaa hakemusta` & `Poista hakemus` buttons
[VEN-1110](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1110): Customer Berths page - Application
- Go through the profile page for the following users:
- Application sent: https://venepaikka.test.kuva.hel.ninja/fi/profile/1
- Offer sent: https://venepaikka.test.kuva.hel.ninja/fi/profile/2 
- Recurring invoices: https://venepaikka.test.kuva.hel.ninja/fi/profile/3
- Invoice Paid: https://venepaikka.test.kuva.hel.ninja/fi/profile/4
- No berths: https://venepaikka.test.kuva.hel.ninja/fi/profile/5
> VEN-1110 | Customer Profile Page Fixes

- package.json
* Remove redundant app launch from browser-test:ci
* The app is already running from the previous steps
> Remove redundant app launch from browser-test:ci

- src/common/applicantDetails/tabs/fragments/FullName.tsx
- src/common/utils/formValidation.ts
* Allow more words in names (5 for first and last name)
* Make validation compatible with browsers that don't support Unicode options for regular expressions
* [VEN-1153](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1153): Customer UI validation error of the customer's name
* Existing tests suggest that the new validation schema works as expected
* All names with 5 words of legally accepted characters should be valid
* Validation should work on iPad
> VEN-1153 | Improve customer name validation

- src/common/types/applicationType.ts
- src/common/utils/constants.ts
- src/common/withApplicationType/__tests__/withApplicationType.test.tsx
- src/common/withApplicationType/withApplicationType.tsx
- src/features/berth/berthFormPage/BerthFormPageContainer.tsx
- src/features/berth/berthFormPage/overview/BerthOverviewInfo.tsx
- src/features/berth/berthFormPage/overview/oldBerthInfo/OldBerthInfo.tsx
- src/features/berth/berthFormPage/overview/oldBerthInfo/OldBerthInfoContainer.tsx
- src/features/berth/berthPage/berthLegend/applicationSelector/ApplicationSelector.tsx
- src/features/berth/berthPage/berthLegend/applicationSelector/ApplicationSelectorContainer.tsx
- src/features/berth/berthPage/berthLegend/applicationSelector/__tests__/ApplicationSelector.test.tsx
- src/features/berth/berthPage/berthLegend/applicationSelector/__tests__/ApplicationSelectorContainer.test.tsx
- src/features/berth/selectedBerthPage/SelectedBerthPage.tsx
- src/features/berth/selectedBerthPage/SelectedBerthPageContainer.tsx
- src/features/berth/selectedBerthPage/__tests__/SelectedBerthPage.test.tsx
- src/features/berth/selectedBerthPage/newApplication/NewApplication.tsx
- src/features/berth/selectedBerthPage/switchApplication/SwitchApplication.tsx
- src/features/berth/selectedBerthPage/switchApplication/SwitchApplicationContainer.tsx
- src/features/berth/selectedBerthPage/switchApplication/__tests__/SwitchApplication.test.tsx
- src/features/berth/selectedBerthPage/switchApplication/switchApplication.scss
- src/features/profile/customerBerths/properties/Property.tsx
- src/features/profile/customerBerths/properties/property.scss
- src/features/winterStorage/selectedAreaPage/SelectedAreaPage.tsx
- src/features/winterStorage/selectedAreaPage/__tests__/SelectedAreaPage.test.tsx
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
* Replace term "exchange" with "switch"
* Fix clashing property component styles (VEN-1290)
* Sort harbor options on SwitchApplication page by name
* Correct OldBerthInfo harbor name
* [VEN-1204](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1204): FE - Customer UI page to accept/reject switch offer
* [VEN-1290](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1290): FE - Padding on service icons on Customer UI
* Properties should render correctly
* Harbor options for old harbors should be sorted by name
* Previous harbor name should be shown correctly (instead of an ID)
> VEN-1204, VEN-1290 | Fixes related to switch offers

- src/__generated__/globalTypes.ts
- src/features/__generated__/AcceptBerthSwitchOffer.ts
- src/features/__generated__/BerthQuery.ts
- src/features/__generated__/HarborPiersQuery.ts
- src/features/__generated__/HarborsQuery.ts
- src/features/__generated__/OrderDetails.ts
- src/features/__generated__/SubmitWinterStorage.ts
- src/features/__generated__/UnmarkedWinterAreasQuery.ts
- src/features/__generated__/WinterAreasQuery.ts
- src/features/payment/berthInfo/BerthInfo.tsx
- src/features/payment/paymentPage/ContractPage.tsx
- src/features/payment/paymentPage/PaymentPage.tsx
- src/features/payment/paymentPage/PaymentPageContainer.tsx
- src/features/payment/winterStorageInfo/WinterStorageInfo.tsx
- src/features/payment/winterStorageInfo/winterStorageInfo.scss
- src/features/queries.ts
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
- Added a new component for displaying WS areas info
- Pass product as a prop to Payment and Contract pages
[VEN-1294](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1294): add ws place/section/area information to the customer UI payment page
- When getting an offer, go to the payment link you received
- The payment page should show the information about the product you're paying for, i.e. berth, WS area
> VEN-1294| Support WS place info on Payment and Contract pages

- src/app/apolloClient.ts
* Expired apiTokens should now be cleared and not be added to header
> Check session with OIDC client before setting apiTokens for query

- src/common/utils/orders.ts
- src/features/payment/cancelOrderPage/CancelOrderPage.tsx
- src/features/payment/cancelOrderPage/CancelOrderPageContainer.tsx
- src/features/payment/paymentPage/ContractPage.tsx
- src/features/payment/paymentPage/PaymentPageContainer.tsx
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
- Fix texts on payment and cancel order pages
- Redirect users w/o order contracts to error page
> VEN-1365 & VEN-1366 | Payment and Cancel Order Pages Fixes

- .env
- .github/workflows/review.yml
- .github/workflows/staging.yml
- src/app/auth/__tests__/__snapshots__/authService.test.ts.snap
- src/features/profile/ProfileDebug.tsx
Switch the staging and review environments to use Kanslia's test Tunnistamo and HKI Profile to be able to test Suomi.fi strong authentication. Requires the same changes to [the backend](https://github.com/City-of-Helsinki/berth-reservations/pull/618) and to [the federation gateway](https://github.com/City-of-Helsinki/berth-federation-gateway/pull/39).
**[VEN-1401](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1401)** 
It is not possible to fully test this before merging, but most parts can be tested locally. 
Currently it is not possible to get PR environments' authentication to actually work with Kanslia's Tunnistamo, but those envs are not working at the moment anyway, so we switch them to Kanslia's Tunnistamo to prevent confusion in the future.
> VEN-1401 | Use Kanslia's test Tunnistamo and HKI Profile in staging env

- CHANGELOG.md
- src/__generated__/globalTypes.ts
- src/app/auth/__tests__/authService.test.ts
- src/app/auth/authService.ts
- src/app/auth/callbackPage/CallbackPage.tsx
- src/features/__generated__/CreateMyBerthProfile.ts
- src/features/queries.ts
Changes the login routine so that a Berth profile is added for the user after login completes.
Things to note:
- At the moment Helsinki profile automatically adds a Helsinki profile and a service connection to Berth when the user logs in with strong authentication
- Same support will be added to weak authentication later on--does not exist yet
- If the user has a Helsinki profile, but does not have a Berth profile, the Berth profile should be created
Extended auth test suite to cover profile token picker utility.
Expect that a Helsinki profile gets created when you login without one
> VEN-1355 | Create berth profile on login

- src/app/auth/callbackPage/CallbackPage.tsx
Provide a currentUser that matches typedefs so that Apollo doesn't raise error on missing ID and stop the after-login-redirect from succeeding.
1. Login
2. Access private route (for instance /profile/:id)
2. Delete api keys from locale storage (emulate their expiration)
3. Refresh
4. Expect login to take place
5. Expect login to hand indefinitely
> VEN-1421 | Provide currentUser that matches typedefs

- src/__generated__/globalTypes.ts
- src/features/profile/berths/Berths.tsx
- src/features/profile/berths/BerthsContainer.tsx
- src/features/profile/berths/__fixtures__/mockData.ts
- src/features/profile/berths/__generated__/BERTHS.ts
- src/features/profile/berths/__generated__/EXTEND_BERTH_APPLICATION.ts
- src/features/profile/berths/__generated__/berthApplicationNodeFragment.ts
- src/features/profile/berths/queries.ts
- src/features/profile/berths/types.ts
- src/features/profile/components/application/Application.tsx
- src/features/profile/components/application/ApplicationNoSuitableBerthsNotice.tsx
- src/features/profile/components/application/application.scss
- src/features/profile/components/application/applicationNoSuitableBerths.scss
- src/features/profile/types.ts
- src/features/profile/winterStorage/__fixtures__/mockData.ts
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
When a user's application is in the status `NO_SUITABLE_BERTHS`, show an UI that allows the user to extend their application--in which case it is set to state `PEDING` and will be reviewed again next year.
Slight adjustments to typo to facilitate new heading order--not sure if the "no berths" should be `h1`, but I labeled it so as it the design suggested it was the highest in the hierarchy.
> VEN-1400 | Allow user to extend application

- src/__generated__/globalTypes.ts
- src/features/__generated__/OfferDetails.ts
- src/features/berthSwitchOffer/BerthSwitchOfferPage.tsx
- src/features/berthSwitchOffer/BerthSwitchOfferPageContainer.tsx
- src/features/berthSwitchOffer/offerError/GeneralOfferErrorPage.tsx
- src/features/queries.ts
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
VEN-1461. These berth details has been missing from the Berth switch offer page since the last big refactor.
This draft PR still needs the types, which can be generated when the open-city-profile directive issues are solved.
> Add the missing offer details query to berth switch offer

- CHANGELOG.md
- src/common/utils/__tests__/formValidation.test.ts
- src/common/utils/formValidation.ts
Allow boat registration number to contain 0.
[VEN-1503](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1503)
> VEN-1503 | Allow 0 in boat registration numbers

- package.json
- src/common/SrOnly/SrOnly.tsx
- src/common/SrOnly/__tests__/SrOnly.test.tsx
- src/common/SrOnly/__tests__/__snapshots__/SrOnly.test.tsx.snap
- src/common/SrOnly/srOnly.module.scss
- src/common/agreement/PrivacyPoliciesAgreement.tsx
- src/common/agreement/privacyPoliciesAgreement.module.scss
- src/common/externalLink/ExternalLink.tsx
- src/common/externalLink/__tests__/ExternalLink.test.tsx
- src/common/externalLink/__tests__/__snapshots__/ExternalLink.test.tsx.snap
- src/common/externalLink/externalLink.module.scss
- src/common/form/Form.tsx
- src/common/formPage/FormPage.tsx
- src/common/wizard/Wizard.tsx
- src/common/wizard/wizard.scss
- src/features/berth/berthFormPage/BerthFormPageContainer.tsx
- src/features/berth/berthFormPage/boatDetails/createBerthBoat/tabs/BerthRegisteredBoat.tsx
- src/features/berth/berthFormPage/boatDetails/createBerthBoat/tabs/fragments/GdprNotes.tsx
- src/features/berth/berthFormPage/boatDetails/createBerthBoat/tabs/fragments/gdprNotes.module.scss
- src/features/berth/berthFormPage/overview/BerthOverview.tsx
- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
- src/setupTests.ts
- yarn.lock
VEN-1275. Show the GDPR -notes on every berth form wizard page (after step 2).
Step 3
Step 4
Step 5
> Show the GDPR -notes on every berth form wizard page

- src/common/registeredBoatDetails/RegisteredBoatDetails.tsx
- src/common/utils/formValidation.ts
This allows users to input both upper- and lowercase letters on boat registration number input, and automatically converts the input value to uppercase.
VEN-1529
> Allow lowercase letters on boat registration number but convert them to uppercase

- src/common/layout/navbar/Navbar.tsx
Hide "profile" tab for now from the navigation for now, since it's not complete yet. If it gets completed, profile can be added back. This is done so Venepaikat can be released from master while moving to Platta.
> hide profile option from navigation

- src/common/card/Card.tsx
- src/features/frontPage/FrontPage.tsx
Hide old trailer payment link from the frontpage for now.
> Ven-1546: Hide trailer payment link

- README.md
refs VEN-1558 (noticed "yarn start" didn't work on Windows)
[VEN-1558](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1558)
[VEN-1558]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add info how to fix SassError on "yarn start" on Windows

- package.json
- src/app/auth/__tests__/__snapshots__/authService.test.ts.snap
- src/app/auth/__tests__/authService.test.ts
- src/common/utils/format.ts
package.json test running:
- make "test:ci" work on its own without dependence on "test:coverage"
- add environment variable settings to "test:watch"
tests:
- fetchApiTokens > should call axios.get with the right arguments
- This test case was dependent on REACT_APP_TUNNISTAMO_URI being set
to https://tunnistamo.test.hel.ninja in the environment
- Removed the dependence by testing against the current value of the
REACT_APP_TUNNISTAMO_URI environment variable in the test
- formatDate > should include time info when the third argument is true
- This test case didn't work on Windows even with TZ=UTC environment
variable was set correctly during the test (Tried it on Windows)
- Fixed on Windows also by using process.env.TZ as the timezone in
formatDate function if process.env.TZ is set
refs …
> test: add robustness (remove env var dependency, use TZ in formatDate)

- src/common/utils/__tests__/format.test.ts
- src/common/utils/format.ts
e.g. previously formatPercentage(25.5, 'en') == '26%', now '25.5%'
also add more tests for formatPercentage
refs VEN-1575 (VAT percentage change to 25.5% as of 2024-09-01)
[VEN-1575](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575)
[VEN-1575]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEN-1575 | Make formatPercentage support 0–3 fractional digits for e.g. 25,5%

- src/locales/en.json
- src/locales/fi.json
- src/locales/sv.json
differences between the different locale versions of palvelukartta:
- servicemap.hel.fi/unit/X redirects to servicemap.hel.fi/en/unit/X
- servicekarta.hel.fi/unit/X redirects -> servicekarta.hel.fi/sv/unit/X
- palvelukartta.hel.fi/unit/X DOES NOT redirect to
palvelukartta.hel.fi/fi/unit/X and thus the URL works incorrectly
refs VEN-1575
[VEN-1575](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575)
[VEN-1575]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VEN-1575 | fix: servicemap URLs so they always have locale
