README.md, package.json, stories/wizardPages.story.js
Add new command to run both React app and Storybook simultaneously + update ReadME file with plugins and better instructions
=> Yarn Develop

.flowconfig, src/components/forms/Wizard.js, src/components/layout/KoroSection.js, src/components/layout/KoroSection.scss, src/components/layout/Layout.js, src/components/pages/BerthPage.js, src/components/pages/ThankYouPage.js, src/config/theme.js, src/translations/fi.json
Improved layout Koro's so they overlap with previous content, then we need to keep in mind that last element of content needs to have margin/padding so content doesn't get overlaid by koro
=> Wizard footer

src/components/forms/fragments/overview/BoatDraughtAndWeight.js, src/components/forms/fragments/overview/BoatInfo.js, src/components/forms/fragments/overview/BoatMeasures.js, src/components/forms/fragments/overview/BoatTypeAndModel.js, src/components/forms/fragments/overview/Person.js, src/components/forms/sections/Overview.js, src/components/forms/sections/OverviewInfo.js, src/components/pages/FormPage.js, src/components/pages/containers/FormPageContainer.js, src/types/berths.js, stories/forms.story.js
- Place boat and person info into their own components
- Use those components in OverViewInfo component
- Updated Storybook
=> Seperate boat and person info into their own components

src/components/Map.js, src/components/berths/Berth.js, src/components/berths/Berths.js, src/components/berths/InvalidSelection.js, src/components/berths/SelectedBerth.js, src/components/berths/SelectedBerths.js, src/components/berths/TabSelector.js, src/components/common/Icon.js, src/components/pages/BerthPage.js, src/components/pages/SelectedBerthPage.js, src/components/pages/containers/SelectedBerthPageContainer.js, src/config/bootstrap.scss, src/translations/fi.json, src/types/ducks.js, src/utils/berths.js
Just basic functionality - MWP for tomorrow. Nothing fancy...
=> Services validation

src/components/forms/SectionSelector.js, src/components/forms/Wizard.js, src/components/forms/sections/ApplicantDetails.js, src/components/forms/sections/BoatDetails.js, src/components/forms/sections/Overview.js, src/components/layout/Layout.js, src/components/legends/BerthsLegend.js, src/components/legends/FormLegend.js, src/components/legends/SelectedBerthsLegend.js, src/components/pages/FormPage.js, src/components/pages/SelectedBerthPage.js, src/components/steps/Step.js, src/components/steps/Steps.js, src/config/bootstrap.scss
- Make content widths consistent across app
- Some typography and mobile width fixes
=> Layout revision

api/resources/harbors.json, src/components/Map.js, src/components/berths/Berth.js, src/components/berths/Berths.js, src/components/berths/TabSelector.js, src/components/common/Icon.js, src/translations/en.json, src/translations/fi.json, src/translations/sv.json, src/types/berths.js
- Style detail and mobile scaling tweaks for berths list
- Added a placemerker for availability level indicator (TODO: make it functional)
=> Berth list styles

src/components/berths/BerthsOnMap.js
Fix map jumping aside on IE11.
=> Ie 11 fixes

Dockerfile, README.md, docker-compose.yml
- Add docker config
- Add instruction on README.
=> KUVA-72 | Dockerized development environment

package.json, yarn.lock
Cleanup last traces of styled-component dependencies. Some custom loader is still in from storybook setup
=> VEN-41 | Remove styled-loader dependencies

src/components/forms/fragments/PostalDetails.js
=> VEN-65 | make address, zip_code and municipality fields mandator

src/components/common/Input/Input.tsx, src/components/forms/sections/ApplicationSelector/ApplicationSelector.tsx
Switch application radio button have label as children instead of label, fixed
=> VEN-77 | Make switch application select radio button label clickable

src/components/forms/fragments/exchangeApplication/ExchangeApplication.tsx, src/components/forms/fragments/newApplication/NewApplication.tsx, src/components/pages/BerthPage/SelectedBerthPage/SelectedBerthPage.tsx
=> VEN-80 | Decrease header size from h1 to h3

public/index.html, src/assets/styles/_normalize.scss, src/components/forms/fragments/StorageAreas.tsx, src/utils/berths.ts
- Normalize all custom input to have fix 2rem like how all hki service padding have. (Discussed with @terotic 
- Fix logic of filter which inverted
- Enable abillity to check both checkboxes
=> VEN-110 | User should be able to click both "appointed spaces" and "free placement"

src/components/common/card/Card.tsx, src/components/common/card/card.scss
- Change card title to h3 and adjust title styles (it should look like before)
- Remove unused import
https://helsinkisolutionoffice.atlassian.net/browse/VEN-494
=> VEN-494 | Change form selection header to h3

src/components/App.tsx, src/components/pages/notFoundPage/NotFoundPage.tsx, src/components/pages/notFoundPage/notFoundPage.scss, src/translations/en.json, src/translations/fi.json, src/translations/sv.json
* Add 404 page
* [VEN-67](https://helsinkisolutionoffice.atlassian.net/browse/VEN-67): FE: add 404 page
=> VEN-67 | Add 404 page

src/components/App.tsx, src/index.tsx
* Use Finnish as fallback locale
* [VEN-67](https://helsinkisolutionoffice.atlassian.net/browse/VEN-67): FE: add 404 page
=> VEN-67 | Use Finnish as fallback locale

CHANGELOG.md, package.json
Merge 0.5.0 release branch into `develop`
=> VEN-738 | Update CHANGELOG & bump up version number

src/components/common/hero/hero.scss, src/components/layout/koroSection/koroSection.scss, src/components/legends/berthLegend/berthLegend.scss, src/components/legends/winterStorageLegend/winterStorageLegend.scss, src/locales/fi.json, src/locales/sv.json
* Fix problems with hyphens on Windows
* [VEN-786](https://helsinkisolutionoffice.atlassian.net/browse/VEN-786): WS customer UI two logos not displaying correctly
=> VEN-786 | Fix problems with hyphens on Windows

src/components/common/card/Card.test.tsx, src/components/common/card/Card.tsx, src/components/common/card/card.scss, src/components/pages/frontPage/FrontPage.tsx, src/components/pages/frontPage/frontPage.scss, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
* Add Nostojärjestys card to front page, with adjustments to appearance
* Fix Thank you page in Finnish and English
* [VEN-740](https://helsinkisolutionoffice.atlassian.net/browse/VEN-740): Add Nostojärjestys card to the home page
* [VEN-789](https://helsinkisolutionoffice.atlassian.net/browse/VEN-789): Fix the application Thank you page title text (FI and ENG)
=> VEN-740 | Add Nostojärjestys card to front page

src/__fixtures__/winterStorageFixture.ts, src/__generated__/globalTypes.ts, src/components/common/areaCard/AreaCard.tsx, src/components/pages/berthPage/BerthCard.tsx, src/components/pages/selectedAreaPage/SelectedAreaPage.tsx, src/components/pages/selectedBerthPage/SelectedBerthPage.tsx, src/components/pages/winterStoragePage/WinterStorageCard.tsx, src/utils/__generated__/BerthSwitchReasonsQuery.ts, src/utils/__generated__/BoatTypesBerthsQuery.ts, src/utils/__generated__/HarborNameQuery.ts, src/utils/__generated__/SubmitBerth.ts, src/utils/__generated__/SubmitWinterStorage.ts, src/utils/__generated__/WinterAreasQuery.ts, src/utils/berths.test.ts, src/utils/berths.ts, src/utils/graphql.ts
* Revert WS query and behavior changes
* Backend had changed erroneously, the original commits reflect them
* Both will be reverted
=> Fix: Revert WS query and behavior changes

.gitlab-ci.yml, CHANGELOG.md, Dockerfile, package.json
- Fix wrong env prop
- Version bump
- Update CHANGELOG.md
=> VEN-792 | Release fixes

src/components/App.tsx, src/components/layout/navbar/Navbar.tsx, src/components/pages/frontPage/FrontPage.tsx, src/components/pages/frontPage/frontPage.scss, src/utils/featureFlags.ts
Remove feature flag from unmarked winter storage.
=> VEN-817 | Remove feature flag from unmarked winter storage

src/components/App.tsx, src/components/pages/formPage/UnmarkedWinterFormPageContainer.tsx, src/components/pages/notice/NoticeSentPage.tsx, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
* Swedish and English translations
* Replace "notification" term with "notice"
* [VEN-758](https://helsinkisolutionoffice.atlassian.net/browse/VEN-758): Add missing translations
=> VEN-758 | Add Swedish and English translations

.dockerignore, .env, .env.production, .gitlab-ci.yml, Dockerfile
* Adjust GitLab pipeline configuration
* Configure Sentry properly
* [VEN-567](https://helsinkisolutionoffice.atlassian.net/browse/VEN-567): Adjust Gitlab pipeline configurations
* [VEN-604](https://helsinkisolutionoffice.atlassian.net/browse/VEN-604): Configure Sentry properly
=> VEN-567, VEN-604 | Adjust GitLab pipeline configuration (customer)

.gitlab-ci.yml
=> VEN-978 | Switch to GH flow

.gitlab-ci.yml
Let staging to be updated from master
=> Switch to GH flow | Let staging to be updated from master

.gitlab-ci.yml
=> VEN-978 | Fix build triggers

browser-tests/berth.ts, browser-tests/unmarkedWinterStorage.ts, browser-tests/winterStorage.ts
* Adjust test chaining to avoid timing issues
* Change unmarked ws browser test area
* [VEN-808](https://helsinkisolutionoffice.atlassian.net/browse/VEN-808): Implement happy path E2E tests for customer UI
=> VEN-808 | Fix browser tests

.github/workflows/production.yml
=> Add additional hostnames block for prod deployment

src/__generated__/globalTypes.ts, src/app/App.tsx, src/components/pages/cancelOrderPage/CancelOrderPage.tsx, src/components/pages/cancelOrderPage/CancelOrderPageContainer.tsx, src/components/pages/cancelOrderPage/cancelOrderPage.scss, src/locales/en.json, src/locales/fi.json, src/locales/sv.json, src/utils/__generated__/CancelOrder.ts, src/utils/graphql.ts
- Implement a page for canceling orders 
- Go to:
- FI: https://venepaikka.test.kuva.hel.ninja/fi/cancel-order
- EN: https://venepaikka.test.kuva.hel.ninja/en/cancel-order
- SV: https://venepaikka.test.kuva.hel.ninja/sv/cancel-order
=> VEN-913 | Cancel order page

.github/workflows/production.yml
=> Add additional hostnames block

package.json
- Bump up thee version number in `package.json`
=> Bump up the version number to 1.2.1

package.json, src/redux/store/configureStore.ts, yarn.lock
* Upgrade react-redux, redux-promise-middleware, husky, graphql
* Other upgrades are blocked by abandoned dependencies
=> Upgrade react-redux, redux-promise-middleware, husky, graphql

src/features/payment/cancelOrderPage/CancelOrderPageContainer.tsx
* Fix redirect on cancel order
* [VEN-1120](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1120): Add success page for cancelling invoice/berth
=> VEN-1120 | Fix redirect on cancel order

.github/workflows/review.yml
* Roll back review workflow triggers
=> Roll back review workflow triggers

.github/workflows/production.yml, .github/workflows/staging.yml
- Use the correct Tunnistamo CLIENT_ID in production & staging
=> Use the correct Tunnistamo CLIENT_ID in production & staging

src/app/auth/authService.ts
- Read the values `UserManager` settings during the initialization
- I am not 100% sure that this will resolve the issue, but I have a strong suspicion that this is the culprit.
=> Fix loading settings issue

src/app/App.tsx, src/app/auth/privateRoute/PrivateRoute.tsx, src/common/layout/navbar/Navbar.tsx, src/common/utils/featureFlags.ts
* Hide authentication and profile pages behind a feature flag
* [VEN-1247](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1247): Hide the authentication and profile pages behind a feature flag
=> VEN-1247 | Hide authentication and profile pages behind a feature flag

src/__generated__/globalTypes.ts, src/app/App.tsx, src/common/utils/urls.ts, src/features/berthSwitchOffer/BerthSwitchOfferPage.tsx, src/features/berthSwitchOffer/BerthSwitchOfferPageContainer.tsx, src/features/berthSwitchOffer/SwitchOfferCompletedPage.tsx, src/features/berthSwitchOffer/__generated__/AcceptBerthSwitchOffer.ts, src/features/berthSwitchOffer/berthSwitchOfferPage.scss, src/features/berthSwitchOffer/mutations.ts, src/features/payment/paymentPage/ContractPage.tsx, src/features/payment/paymentPage/PaymentPage.tsx, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
* Two new pages:
* `/offer`
* `/offer-thank-you`
* [VEN-1204](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1204): FE - Customer UI page to accept/reject switch offer
=> VEN-1204 | Accept and decline berth switch offers

package.json
* Increment package version to 2.0.1
=> Increment package version to 2.0.1

package.json
Bump up the version number to 2.0.2
=> Bump up version number to 2.0.2

browser-tests/berth.ts, src/__generated__/globalTypes.ts, src/features/__generated__/UpdateProfile.ts, src/features/profile/MockProfilePageContainer.tsx, src/features/profile/ProfilePage.tsx, src/features/profile/ProfilePageContainer.tsx, src/features/profile/__fixtures__/mockData.ts, src/features/profile/contactInfo/ContactInfo.tsx, src/features/profile/contactInfo/ContactInfoContainer.tsx, src/features/profile/contactInfo/EditContactInfo.tsx, src/features/profile/contactInfo/editContactInfo.scss, src/features/profile/types.ts, src/features/profile/utils.ts, src/features/queries.ts, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
* Edit customer contact information
* [VEN-1103](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1103): Edit customer contact information
* Log in
* Create profile
* Link Venepaikat service to profile
* Edit profile information
=> VEN-1103 | Update profile contact information

src/locales/sv.json
- Fix Swedish translations on the payment page
=> VEN-1366 | Fix Swedish text on payment page

package.json
=> Bump up version number

.env, .github/workflows/production.yml, .github/workflows/review.yml, .github/workflows/staging.yml, package.json, src/common/card/Card.tsx, src/common/icon/Icon.tsx, src/common/icon/icons/link-external.svg, src/features/frontPage/FrontPage.tsx, src/features/frontPage/frontPage.scss, src/features/terms/TermsOfService.tsx, src/features/terms/termsOfService.scss, src/index.tsx, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
- Implement Terms Of Service Page
- Update Card component to support external links
- Add trailer card to FrontPage & fix styles
- On the front page, a new card is added
- Follow the link on the card to proceed with the payment
=> VEN-1370 & VEN-1371 | Support Trailer Talpa Payment

src/features/terms/TermsOfService.tsx
=> VEN-1370 | Fix payment terms

.github/workflows/production.yml, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
* Updates url in trailer description
* Updates trailer payment link
This PR can be used for review. When it is merged, this change is integrated into the main branch that can't currently be released. This change can't be released from the main branch.
This change can be released from this branch: https://github.com/City-of-Helsinki/berth-reservations-ui/pull/426
[VEN-1475](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1475)
=> VEN-1475 | Update trailer summer storage payment card content

src/features/berth/berthPage/BerthPage.tsx
Fix sorting of harbors list to be in alphabetical order
=> VEN-1497: Harbors list sorting

.github/workflows/production.yml, .github/workflows/review.yml, .github/workflows/staging.yml
Increase k8s cpu limit
DEVOPS-402 CPU Throttling high alerts
=> DEVOPS-402 increase k8s cpu limit to 15m

.prod/nginx.conf, Dockerfile
=> Openshift write permission DEVOPS-481

.env, Dockerfile, src/features/terms/TermsOfService.tsx, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
=> fix: summer trailer texts for 2023

package.json
=> chore: testcafe report path

azure-pipelines-venepaikat-test.yml, package.json
=> chore: test pipeline trigger branch name

.gitignore, package.json, yarn.lock
=> chore: testcafe video recording

src/locales/en.json, src/locales/fi.json, src/locales/sv.json
=> fix: 2024 translations

src/locales/en.json, src/locales/sv.json
=> fix: missing translations

README.md, src/__fixtures__/harborFixture.ts, src/__fixtures__/winterStorageFixture.ts, src/features/profile/ProfileDebug.tsx, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
refs VEN-1575
refs VEN-1575
[VEN-1575](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575)
[VEN-1575]: https://helsinkisolutionoffice.atlassian.net/browse/VEN-1575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VEN-1575 | fix: incorrect URLs with correct ones

.env, src/locales/en.json, src/locales/fi.json, src/locales/sv.json
VEN-1600.
Update summer storage payment card's header, content and URL for payment link for year 2025.
Pipeline changes in:
https://dev.azure.com/City-of-Helsinki/venepaikat/_git/venepaikat-pipelines/pullrequest/11147.
=> feat: update trailer payment URL

src/app/auth/__tests__/authService.test.ts, src/common/discontinuationNotice/DiscontinuationNotice.tsx, src/common/hero/Hero.tsx, src/common/layout/navbar/__tests__/Navbar.test.tsx, src/common/utils/featureFlags.ts, src/features/winterStorage/winterStoragePage/WinterStoragePage.tsx, src/locales/en.json, src/locales/fi.json, src/locales/sv.json, yarn.lock
VEN-1959.
Add discontinuation notification above the hero element below the navigation bar.
Some other miscallenous changes:
- Disable login in all envs
- Upgrade HDS-React to latest v1 (to fix Notification component rendering)
- Fix some linter issues
---- 
Screenshots
Finnish frontpage:
Swedish frontpage:
English frontpage:
Some other pages:
Mobile view:
=> Add discontinuation notification above the hero element
